version: '4.12'
services:
 dbpostgresql:
   container_name: postgres_container
   networks:
     - order-pgsql
   image: postgres:latest
   restart: always
   environment:
     POSTGRES_DB: paymentdb
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     PGDATA: /var/lib/postgresql/data
   expose:
     - 5432
   ports:
     - 5432:5432
   volumes:
     - db-data:/var/lib/postgresql/data

 pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:5.5
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin

 app:
   container_name: springbootapp
   image: springbootapp:latest
   networks:
     - order-pgsql
   expose:
     - 8081
   ports:
     - 8081:8081
   depends_on:
     - dbpostgresql
   environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/paymentdb
     - SPRING_DATASOURCE_USERNAME=postgres
     - SPRING_DATASOURCE_PASSWORD=postgres

networks:
  order-pgsql:
volumes:
 db-data:
 pgadmin-data: